### ISSUE TITLE
Vote accepts the possible votes as new vote subject when a vote is not active

### ISSUE THREAD

**Issue by cntrlwiz** [wardellchandler/HangoutsBot#19]
A test in one of my conversations revealed this bug.  I had conducted a vote that I cancelled prior to completion.  Another user did "/vote no" attempting to vote, and the bot responded by starting a new vote with the subject "no".
Starting a new vote should require something like /vote start <subject>.

**Comment by wardellbagby** [comment]
@cntrlwiz I ran into this a few times myself, but I'm not sure how I feel about /vote start versus /vote "subject" here.

I've been trying to stray away from having commands have too many subcommands in them, but I'm going to implement this change anyway and see how my test group feels about it. 

At the very least, I will change around the logic so that doing "/vote <vote subcommand>" will never start a new vote, but adding in /vote start will be left at their discretion.

**Comment by cntrlwiz** [comment]
Agreed, but for general use there is another concern that I believe drives the need for a "start" subcommand.
As you can imagine, some users are quite playful, and they might type things like "/vote idgaf", "/vote f-that", "/vote hellyeah" and other frivolous responses.  If a vote isn't active, they'll start one.
You can't restrict "/vote" to an admin, but I'm wondering if you could restrict "/vote start"?

**Comment by wardellbagby** [comment]
@cntrlwiz  That's actually on my todo list. I have the logic in place such that I know it is possible, but I need to come up with a way to structure that in the config file such that:

A: It doesn't break any existing forks' config files and
B: Intuitively makes sense, while also being precise enough that I can guarantee that that's what the bot master meant to block.

I'm thinking something along the lines of:

"commands_admin" : ["hangouts", "block", "vote start", "record *"]

So the commands /hangouts, /block, /vote start, and all subcommands of /record but not record itself would be blocked. 

I haven't putten any of this to code yet, though. How do you feel about it?

**Comment by cntrlwiz** [comment]
That sounds like a good strategy.  
As the bot gains features, complication is inevitable.  It just needs to be managed.
