### ISSUE TITLE
Clarify what differs in this fork

### ISSUE THREAD

**Issue by davidkassa** [wardellchandler/HangoutsBot#40]
What differs on this fork from the one you mention in the readme?

**Comment by wardellbagby** [comment]
I don't keep a lot of tabs on @xmikos's version but at the core, we perform the same task. We're both bots that connect to Hangouts in order to respond to text with certain results. We both allow developers to expand upon the default functionality by adding in new features. 

@xmikos is a better programmer than I am, so I would say that his fork would probably be more easily extended and likely more stable. When I picked this up, I didn't know how forking worked, so I cloned it and make it my own repo instead of forking his like I should've, but I digress.

I update mine a bit more often than @xmikos does, and I might be more vocal with forks of mine than he is with his, but I really don't know for sure. 

I think the only real perk for my forks versus his is that mine comes with Cleverbot support out of the box, haha. 

Also, I think another difference is that his commands are ran as "/bot help" and mine are ran as "/help," but that might be an option on his that you can change, as it's an option on mine that you can change.

If you're trying to decide which to use as your bot as a developer/user, I think you should go with his. Most of my commands should be able to be converted to his format, since they share a base. All you should have to do is change the annotation. 

That being said, I have a little bit of a family here with my forks (which, if you play Ingress, you should check out @cntrlwiz, and @ShaunOfTheLive has a ton more commands than both @xmikos and I!) and I'm always happy to help out another dev or a user solve an issue they might have.

Also, @nylonee has arguably the most feature comprehensive and largest Hangouts bot on Github, and he forked from @xmikos, so you may want to check on that.

I hope that helps!

**Comment by davidkassa** [comment]
Thanks! I'm not quite sure what I'm going to do yet. I created the hubot-slack-relay for slack-to-slack server communication and now people are asking for hangouts integration. I might just go directly against hangups or hangupsjs since hubot and hangoutbot seem to have a high level of redundancy.

The call-outs to the other devs are great. They have good stuff to see. Great feedback!

**Comment by cntrlwiz** [comment]
The one advantage that hubot has is the ability to run on Heroku.  I haven't figured out how to make hangups/HangoutsBot work on that system, so I'm hosting it on a personal server for my Hangouts conversations.

**Comment by nylonee** [comment]
@davidkassa The [hangoutsbot](https://github.com/hangoutsbot/hangoutsbot) that I forked allows hubot integration, admittedly a little primitively. There's also a great team working on that bot.

I must confess though, a lot of the functionality that I added was inspired by this [HangoutsBot](https://github.com/wardellchandler/HangoutsBot) =) (like CleverBot)
